---
stages:
  - lint
  - build
  - create release
  - publish

variables:
  ARTIFACT_DIR: "artifacts-$CI_COMMIT_SHORT_SHA"

image: registry.gitlab.com/woofball/woof-docker:latest

.inject_key: &inject_key
    - echo "Injecting Google Maps API key..."
    - echo "api.token=${GOOGLE_API_TOKEN}" >> $CI_PROJECT_DIR/src/android/local.properties

default:
  before_script:
    - export
    - flutter --version
    # currently all jobs need to run from the src dir
    # this could change, so here's a comment to remind everyone
    - mkdir -p ${ARTIFACT_DIR}
    - cd src/

lint:
  stage: lint
  script:
    - flutter analyze
  only:
    changes:
      - lib/*.dart
      - lib/**/*.dart
  when: always

build debug:
  stage: build
  script:
    - *inject_key
    - flutter build apk --split-per-abi
    - ls -la build/app/outputs/apk/release
    - mkdir -p ../${ARTIFACT_DIR}/apk
    - mv build/app/outputs/apk/* ../${ARTIFACT_DIR}/apk
  artifacts:
    paths:
      - "${ARTIFACT_DIR}/**"
    expire_in: 2 days
  when: manual
  except:
    - master
    - tags

build apk release:
  stage: build
  script:
    - *inject_key
    - flutter build apk --split-per-abi
    - ls -la build/app/outputs/apk/release
    - mkdir -p ../${ARTIFACT_DIR}/apk
    - mv build/app/outputs/apk/release/* ../${ARTIFACT_DIR}/apk
  artifacts:
    paths:
      - "${ARTIFACT_DIR}/**"
    expire_in: 2 days
  only:
    - master
    - tags

build appbundle release:
  stage: build
  script:
    - *inject_key
    - flutter build appbundle
    - ls build/app/outputs/bundle/release
    - mkdir -p ../${ARTIFACT_DIR}/appbundle
    - mv build/app/outputs/bundle/release/* ../${ARTIFACT_DIR}/appbundle
  artifacts:
    paths:
      - "${ARTIFACT_DIR}/**"
    expire_in: 2 days
  only:
    - master
    - tags
